services:
  - type: worker
    name: poputchik-bot
    runtime: python
    repo: https://github.com/Isropil1859/poputchik_bot
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8270928147:AAEz1zbYarSM_PFe7v3V6gmZ2-6TBjkh8lA
    plan: starter